name: test_otdapaper
channels:
  - conda-forge
  - defaults
dependencies:
  - autograd=1.3
  - autopep8=1.5.4
  - flake8=3.8.4
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mne=0.19.0
  - numpy=1.19.5
  - numpydoc=1.1.0
  - pandas=1.2.1
  - pip=21.0
  - pot=0.7.0
  - python=3.7.9
  - rtree=0.9.7
  - scipy=1.1.0
  - setuptools=49.6.0
  - statsmodels=0.11.1
  - scikit-learn=0.22.2
  - jupyter
  - pip:
    - pymanopt==0.2.3
    - pyriemann==0.2.6
    - scikit-posthocs==0.6.5
    - seaborn==0.10.0
    - statannot==0.2.3